---
- hosts: deploy
  become: no
  gather_facts: no
  vars:
    docker_registry_password: "#valli27"

  tasks:
    - name: Login to docker registry
      shell: echo "{{ docker_registry_password }}" | docker login -u pravallikamahesh --password-stdin https://index.docker.io/v1/
    
    - name: pull image from docker hub
      shell: docker pull pravallikamahesh/sujatha:tagname

    - name: docker run
      shell: docker run --init -d pravallikamahesh/sujatha:tagname