
on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: prav
        
        steps:
           
            - uses: actions/checkout@v4
            
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t pravallikamahesh/sujatha:tagname .
                docker push pravallikamahesh/sujatha:tagname


            - name: run ansible playbook
              if: github.ref == 'refs/heads/master'
              env:
                 password: ${{ secrets.DOCKER_PASSWORD }}
              run: |
                ansible-playbook ansible.yml -i sasi.txt --extra-vars "password=$password"
