
on: 
    push:
        branches: [master]
    

jobs:
    build:
        runs-on: ubuntu-latest
        
        steps:
            - run: node --version
            - run: npm --version
            - uses: actions/checkout@v4
            
            
            - name: Log in to Docker Hub
              run: |
                echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                docker image build -t pravallikamahesh/dataphionc:tagname .
                docker push pravallikamahesh/dataphionc:tagname